### PR TITLE
Fixes stream.h include so it can be found.

### PR DESCRIPTION
**Pull request by mlopezqc**
While working on another project I started having issues with your latest code. I found that the recently added stream.h was not added to the CMakeList.txt and it was not well referenced in the assert.c file. I fixes those for my project.

### CODE REVIEW

**Comment by Snaipe** [comment]
Good catch for the CMakeLists.txt bit, but I don't get why the `#include` needs to be changed; the header is in `criterion/new`, so it should be including `criterion/new/stream.h`. Is it not working on your end?

**Comment by Snaipe** [comment]
All the builds are failing with that change, so I don't think it's the right fix. What was the original problem that prompted this fix?

**Comment by stdevMauricio** [comment]
I seems to me that not including stream.h in the CMakeList was the source of the errors. There are two of them, so I got confused. I'd recommend you to delete the src/include folder before running the tests, so the compiler is forced to use the installed libraries and early detect if there's something missing in CMakeList. Sorry if I didn't make an issue, but I'm really short on time. Just hope this helps.

**Comment by Snaipe** [comment]
Alright, looks good to me (the new build errors are unrelated). Thanks for the fix!

**Comment by Snaipe** [comment]
Rebased & merged as 97d6ec7.

**Pull request closed without merging**
