### PR TITLE
Rewrite the I/O logic and define a protocol

### PR DESCRIPTION
**Pull request by Snaipe**
This is mostly here to discuss and test anything related to the new protocol definition and the rewrite of the I/O logic.

The scope of this PR is to implement a client/server model, to start implementing the feature request #69.

The current technologies under test are:
* Protocol definition using the protobuf DSL.
* Protobuf implementation provided by nanopb.
* I/O abstraction provided by nanomsg.

nanopb should be more adequate than libprotobuf for serialization, as there seems to be a lot of effort done to make in run on embedded systems.

### CODE REVIEW

**Comment by Snaipe** [comment]
The current protocol definition can be found [here](https://github.com/Snaipe/Criterion/blob/features/io-rewrite-nanopb/src/protocol/criterion.proto)

**Comment by ckaran** [comment]
Looks good!  Although if you're going with protocol buffers, do you need the version field?  Protocol buffers support a method of updating messages: https://developers.google.com/protocol-buffers/docs/proto3#updating.  That said, I don't know what [nanopb](http://koti.kapsi.fi/jpa/nanopb/) supports in terms of updated messages, so it may still be necessary.

**Comment by Snaipe** [comment]
The version field is mostly here to allow updated versions of the protocol that would be otherwise breaking backward compatibility -- although it might never be used at all, its just a safeguard. Message updating will still be used within a protocol version.

**Comment by ckaran** [comment]
OK, but isn't that the point of protocol buffers?  So that you can detect if you have backwards-incompatible changes and deal with them in a sane manner?  Or maybe I'm wrong... Eh, you're probably right, even if protocol buffers are able to deal with it, as human beings we like to see what version we're dealing with.  I withdraw the comment! :-)

**Comment by Snaipe** [comment]
If you have backward-incompatible changes with protobuf, you're kinda screwed because the implementation deserialize the message as the new protocol regardless. This is why they tell you to never do that by never reusing field numbers (or making them reserved if you remove some), and not adding new required fields.

**Comment by Snaipe** [comment]
The usage of nanomsg for the purpose of this rewrite might be compromised. I'm waiting for confirmation on my fears from the developers themselves, but here's the gist of it:

* nanomsg internally heavily uses threads and mutexes
* they don't register a pthread_atfork handler to release all associated mutexes and put the library in a 'forkable' state.

This means that nanomsg is effectively unusable after a fork since all mutexes are inherited by the fork, and the child might have resumed when one of the threads was in a critical section.

This issue, coupled to the inheritance semantics of file handles on windows, makes it excruciatingly hard to find a proper I/O library that fits our need.

Hence, I'm going to try two things:

1. Discuss this further with the developers of nanomsg in the hope that we can find a reasonable workaround for this issue,
2. Or, if the above attempt definitely isn't leading anywhere, implement my own I/O library for the express purpose of being fork()'able and reliable on all platforms.

And now, we wait.

**Comment by ckaran** [comment]
Man, I really hope that there is a good way to handle fork().  The only thing I've found so far about it is http://www.freelists.org/post/nanomsg/threading-guidelines-and-is-traditional-unix-single-threaded-mode-possible.  It suggests closing all nanomsg sockets before forking, but I'm not sure how IPC is handled afterwards.  Is it possible to open the sockets after the fork?  With luck, things have changed for the positive in the intervening year+...

**Comment by Snaipe** [comment]
I forked nanomsg and started to fix the fork behaviour. A PR reporting the work in progress can be found at nanomsg/nanomsg#587.

Currently, the rewrite is almost done -- the only thing left is extensive testing.

The new protocol defines a much more rich test lifecycle, but I purposely restricted its interpretation on the runner side for backward compatibility purposes -- it will likely grow out of it for the 3.0.0 release.

the ReportHook API will most likely be deprecated and removed for 3.0.0 -- a replacement will be set up, that properly handles nested subtest phases as defined by the protocol.

**Comment by Snaipe** [comment]
I'm going to merge this into bleeding -- the only bugs left come from the WIP on fork support for nanomsg and will be fixed in time. However, as there is a maintainer change undergoing over nanomsg and hence slower processing of PRs and reviews, and because the bleeding branch is slowly diverging from the changes introduced by the rewrite, it becomes necessary to merge the changes and iterate further on the new bleeding branch.

**Comment by am11** [comment]
:+1:

**Comment by ckaran** [comment]
I'm coming to the party late, but :+1:  :)

**Pull request merged**
