### PR TITLE
Feature: User-defined dataset driven tests

### PR DESCRIPTION
**Pull request by Snaipe**
From the discussion at https://github.com/Snaipe/Criterion/issues/40, a use-case has come to light:

>  [...] to implement parameterized tests, that would iterate over a user-generated dataset rather than the cartesian product of many datasets.

Also, this will run a separate test for each member of dataset and hence yield better result stats.

e.g. current approach is to enumerate over `TheoryDataSet` placeholder data array, which results in:

>
[====] Synthesis: Tested: 1 | Passing: 0 | Failing: 1 | Crashing: 0

for 1276 data items tested out of which (for example) only 26 are failing. 

With `ParameterizedTest` feature, we expect to get:

>
[====] Synthesis: Tested: 1276 | Passing: 1250 | Failing: 26 | Crashing: 0

### CODE REVIEW

**Comment by Snaipe** [comment]
It seems the hub utility chocked on the number of commits included for the merge, the pull request has been recreated at #44.

**Comment by am11** [comment]
Today is a mystery day. This is my first day to learn that it is possible to convert an existing issue to a pull request on GitHub. "How?" is still a mystery. It took me sometime to confirm that I indeed opened an issue, not a PR. :smile:

**Comment by Snaipe** [comment]
@am11 you can convert any issue to a pull request with the [hub](https://github.com/github/hub) CLI utility:

```
hub pull-request -b <base branch> -i <issue number>
```

**Comment by am11** [comment]
Excellent! Will give it a try. Thanks for sharing [`git + hub = GitHub`](https://github.com/github/hub#git--hub--github). :)

**Pull request closed without merging**
